# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Intro to Java
description: This is the homepage of the "Intro to Java" course at ReDI School
footer_content: "Made with ❤ by teachers at <a href=\"https://www.redi-school.org\">ReDI School</a>."
aux_links:
  "Code editor at codeboard.io":
    - "https://codeboard.io/"
  "Glossary":
    - "/intro-java/glossary"
  "Using IntelliJ":
    - "/intro-java/intellij"

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs@v0.3.1-r
color_scheme: redi

# Exclude build and bundle files
# In addition, you can hide some topics
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - meta
  - projects/tic-tac-toe
  - projects/quiz
  - projects/covid19
  - projects/bvg
  - projects/mastermind
  - projects/blackjack
  - review
